### ISSUE TITLE
Gulp task for production build

### ISSUE THREAD

**Issue by kogakure** [kogakure/website-hugo-kogakure.de#58]
To generate an optimized production build, some steps are necessary:

- [x] Clean `dist` folder (#57)
- [x] Generate styles (#59)
- [x] Generate Hugo site (#61)
- [x] Generate production scripts with Webpack (#62)
- [x] Optimize/minimize HTML (#63)
- [x] Optimize/minimize CSS (#64)
- [x] Revisioning of all assets (#66)
- [x] Collect and replace revisioned paths (#67)
